clc;
clear;
close all;

% filename_1 = 'Z:\USV_datasets\data10.13\ch1\T0000001.wav';
% filename_2 = 'Z:\USV_datasets\data10.13\ch2\T0000001.wav';
% filename_3 = 'Z:\USV_datasets\data10.13\ch3\T0000001.wav';
% filename_4 = 'Z:\USV_datasets\data10.13\ch4\T0000001.wav';
file_path = 'Z:\USV_datasets\voice-image\0302\';
f = figure('color','w');
% hold on;

for num = 4
    for ii = 0:10
        
% filename_1 = char(file_path+"ch1\2023-03-02_16-09-22_000"+num+".wav");
% filename_2 = char(file_path+"ch2\2023-03-02_16-09-22_000"+num+".wav");
% filename_3 = char(file_path+"ch3\2023-03-02_16-09-22_000"+num+".wav");
% filename_4 = char(file_path+"ch4\2023-03-02_16-09-22_000"+num+".wav");
filename_1 = char(file_path+"ch1\2023-03-02_16-08-51_000"+num+".wav");
filename_2 = char(file_path+"ch2\2023-03-02_16-08-51_000"+num+".wav");
filename_3 = char(file_path+"ch3\2023-03-02_16-08-51_000"+num+".wav");
filename_4 = char(file_path+"ch4\2023-03-02_16-08-51_000"+num+".wav");

Fs=250000;  % Hz
verbosity = 1;

[y_1_1,~] = audioread(filename_1);
% [y_2,Fs_2] = audioread(filename_2);
% [y_3,Fs_3] = audioread(filename_3);
% [y_4,Fs_4] = audioread(filename_4);

if length(y_1_1)<=0.05*Fs
%     samples = [max(1/Fs,round(((find(y_1_1==max(y_1_1))/Fs)*1000-5)*Fs/1000)),...
%     min(round(((find(y_1_1==max(y_1_1))/Fs)*1000+5)*Fs/1000),length(y_1_1))];
    samples = [round(length(y_1_1)/2-1250),round(length(y_1_1)/2+1250)];
    else
    samples = [1,length(y_1_1)-1];
    samples = [1+ii*10,1000+ii*13]*Fs/1000;
end
% samples = [3750,length(y_1_1)-3750];
[y_1,Fs_1] = audioread(filename_1,samples);
[y_2,Fs_2] = audioread(filename_2,samples);
[y_3,Fs_3] = audioread(filename_3,samples);
[y_4,Fs_4] = audioread(filename_4,samples);

Y = fft(y_1);
Z=abs(Y);
% plot(Z) 
[ma, I]=max(Z);   %ma为数组的�?大�?�，I为下标�??
f_max=floor(I/length(Z)*Fs);

% fprintf(1, '信号频率�?强处的频率�??=%f\n',floor(I/length(Z)*Fs));
n_mikes=4;
% fs=250000;  % Hz
% f_lo=max(15000,f_max-15000);  % Hz
% f_lo=15000;
f_lo = 0;
f_hi=inf;  % Hz
Temp=25;  % C
dx=250e-6;  % m
xl=[-0.50 +0.5];
yl=[-0.5 +0.5];

R1_x=+0.45;
R1_y=0;
R1_z=0.38;

R2_x=0;
R2_y=0.45;
R2_z=0.38;

R3_x=-0.45;
R3_y=0;
R3_z=0.38;

R4_x=0;
R4_y=-0.45;
R4_z=0.38;

% make some grids and stuff做网络格
x_line=(xl(1):dx:xl(2))';
y_line=(yl(1):dx:yl(2))';
n_x=length(x_line);
n_y=length(y_line);
x_grid=repmat(x_line ,[1 n_y]);
y_grid=repmat(y_line',[n_x 1]);

% everything in the case
in_cage=true(size(x_grid));

% colors for microphones
clr_mike=[0 0   1  ; ...
          0 1 0  ; ...
          1 0   0  ; ...
          0.8 0.8 0.8];
%% 4通道
v_1234=[y_1,y_2,y_3,y_4];

R=[ R1_x R1_y R1_z ; ...
    R2_x R2_y R2_z ; ...
    R3_x R3_y R3_z ; ...
   R4_x R4_y R4_z]';  % m

% estimate the mouse position with the true mic positions
[r_est_1234,rsrp_max_1234,rsrp_grid,a,vel,N_filt,V_filt,V]= ...
  r_est_from_clip_simplified(v_1234,Fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity);

% make a figure of that
% [fig_h,axes_h,axes_cb_h]= ...
%   figure_objective_map(x_grid,y_grid,rsrp_grid, ...
%                        'jet', ...
%                        [], ...
%                        'Estimate with true mic positions', ...
%                        'RSRP (V^2)', ...
%                        clr_mike, ...
%                        [1 1 1], ...
%                        r_est_1234,[], ...
%                        R,r_est_1234,r_est_1234+[-0.08 0]');

%% 3_1通道-234
v_234=[y_2,y_3,y_4];
verbosity=0;
R=[ 
    R2_x R2_y R2_z ; ...
    R3_x R3_y R3_z ; ...
   R4_x R4_y R4_z]';  % m

% estimate the mouse position with the true mic positions
[r_est_234,rsrp_max_234,rsrp_grid,a,vel,N_filt,V_filt,V]= ...
  r_est_from_clip_simplified(v_234,Fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity);

% make a figure of that
% [fig_h,axes_h,axes_cb_h]= ...
%   figure_objective_map(x_grid,y_grid,rsrp_grid, ...
%                        'jet', ...
%                        [], ...
%                        'Estimate with true mic positions', ...
%                        'RSRP (V^2)', ...
%                        clr_mike, ...
%                        [1 1 1], ...
%                        r_est_234,[], ...
%                        R,r_est_234,r_est_234+[-0.08 0]');
%% 3_2通道-134
v_134=[y_1,y_3,y_4];
verbosity=0;
R=[ 
    R2_x R2_y R2_z ; ...
    R3_x R3_y R3_z ; ...
   R4_x R4_y R4_z]';  % m

% estimate the mouse position with the true mic positions
[r_est_134,rsrp_max_134,rsrp_grid,a,vel,N_filt,V_filt,V]= ...
  r_est_from_clip_simplified(v_134,Fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity);

% make a figure of that
% [fig_h,axes_h,axes_cb_h]= ...
%   figure_objective_map(x_grid,y_grid,rsrp_grid, ...
%                        'jet', ...
%                        [], ...
%                        'Estimate with true mic positions', ...
%                        'RSRP (V^2)', ...
%                        clr_mike, ...
%                        [1 1 1], ...
%                        r_est_134,[], ...
%                        R,r_est_134,r_est_134+[-0.08 0]');
%% 3_3通道-124
v_124=[y_1,y_2,y_4];
verbosity=0;
R=[ R1_x R1_y R1_z ; ...
    R2_x R2_y R2_z ; ...
   R4_x R4_y R4_z]';  % m

% estimate the mouse position with the true mic positions
[r_est_124,rsrp_max_124,rsrp_grid,a,vel,N_filt,V_filt,V]= ...
  r_est_from_clip_simplified(v_124,Fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity);

% make a figure of that
% [fig_h,axes_h,axes_cb_h]= ...
%   figure_objective_map(x_grid,y_grid,rsrp_grid, ...
%                        'jet', ...
%                        [], ...
%                        'Estimate with true mic positions', ...
%                        'RSRP (V^2)', ...
%                        clr_mike, ...
%                        [1 1 1], ...
%                        r_est_124,[], ...
%                        R,r_est_124,r_est_124+[-0.08 0]');
%% 3_4通道-123
v_123=[y_1,y_2,y_3];

R=[ R1_x R1_y R1_z ; ...
    R2_x R2_y R2_z ; ...
   R3_x R3_y R3_z]';  % m

% estimate the mouse position with the true mic positions
[r_est_123,rsrp_max_123,rsrp_grid,a,vel,N_filt,V_filt,V]= ...
  r_est_from_clip_simplified(v_123,Fs, ...
                             f_lo,f_hi, ...
                             Temp, ...
                             x_grid,y_grid,in_cage, ...
                             R, ...
                             verbosity);

% make a figure of that
% [fig_h,axes_h,axes_cb_h]= ...
%   figure_objective_map(x_grid,y_grid,rsrp_grid, ...
%                        'jet', ...
%                        [], ...
%                        'Estimate with true mic positions', ...
%                        'RSRP (V^2)', ...
%                        clr_mike, ...
%                        [1 1 1], ...
%                        r_est_123,[], ...
%                        R,r_est_123,r_est_123+[-0.08 0]');
%% 离群�?
% point_all=[r_est_1234,r_est_234,r_est_134,r_est_124,r_est_123];
% dis_1234=sqrt(r_est_1234(1)^2+r_est_1234(2)^2);
% dis_234=sqrt(r_est_234(1)^2+r_est_234(2)^2);
% dis_134=sqrt(r_est_134(1)^2+r_est_134(2)^2);
% dis_124=sqrt(r_est_124(1)^2+r_est_124(2)^2);
% dis_123=sqrt(r_est_123(1)^2+r_est_123(2)^2);
% dis=[dis_1234,dis_234,dis_134,dis_124,dis_123];
% % TF = isoutlier(dis,"median","ThresholdFactor",3);
% figure;
% x = 1:5;
% [TF,L,U,C] = isoutlier(dis,'quartiles',"ThresholdFactor",1.5);
% plot(x,dis,x(TF),dis(TF),'x',x,L*ones(1,5),x,U*ones(1,5),x,C*ones(1,5))
% legend('Original Data','Outlier','Lower Threshold','Upper Threshold','Center Value')
%%
R=[ R1_x R1_y R1_z ; ...
    R2_x R2_y R2_z ; ...
    R3_x R3_y R3_z ; ...
   R4_x R4_y R4_z]'; 
figure(f);
hold on;
scatter(R(1,:),R(2,:),'o','k','filled');

scatter(r_est_1234(1),r_est_1234(2),'o','r','filled');
aa = [r_est_234,r_est_134,r_est_124,r_est_123];

for i = 1:5
%     estimates_temp = cell2mat(source_estimated(i,:));
    scatter(aa(1,:),aa(2,:));
    
    
end


axis([-0.52 0.52 -0.52 .52]);
% title("SSL results from seg: "+ num...
%     +" Time: "+samples(1)/time_resolution+"-"+samples(2)/time_resolution+ "ms");
f.InnerPosition = [785.0000  289.8000  560.0000  484.0000];
ax = gca;
ax.Position = [0.1500    0.1100    0.7    0.8];
% ��Բ�α߿�
circle_center = [0 0];
R = 0.52;
t = 0:0.01:2*pi+0.01;
x = R*cos(t);
y = R*sin(t);
plot(x,y,'k','LineWidth',2);
hold off
    end
end




